#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any


GENERATOR_VERSION = "0.1.0"
REQUIRED_SCHEMA_KEYS = ("$schema", "$id", "title", "type", "properties")
SCHEMA_GLOBS = (
    "packages/contracts/domain/*.schema.json",
    "packages/contracts/events/*.schema.json",
    "packages/contracts/optimization/*.schema.json",
    "packages/contracts/calibration/*.schema.json",
)

ROOT = Path(__file__).resolve().parents[1]
CSharp_OUT = ROOT / "packages/contracts/generated/csharp/Contracts.Generated.cs"
PYTHON_OUT = ROOT / "packages/contracts/generated/python/contracts_generated.py"
MANIFEST_OUT = ROOT / "packages/contracts/generated/manifest.json"


def schema_paths() -> list[Path]:
    paths: list[Path] = []
    for pattern in SCHEMA_GLOBS:
        paths.extend(ROOT.glob(pattern))
    return sorted(paths, key=lambda path: path.as_posix())


def load_schema(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        schema = json.load(handle)
    missing = [key for key in REQUIRED_SCHEMA_KEYS if key not in schema]
    if missing:
        rel_path = path.relative_to(ROOT).as_posix()
        raise ValueError(f"{rel_path} missing required keys: {', '.join(missing)}")
    if not isinstance(schema["properties"], dict):
        rel_path = path.relative_to(ROOT).as_posix()
        raise ValueError(f"{rel_path} properties must be an object")
    return schema


def json_type(schema_property: dict[str, Any]) -> str:
    type_value = schema_property.get("type")
    if isinstance(type_value, list):
        return str(type_value[0])
    if isinstance(type_value, str):
        return type_value
    return "object"


def csharp_type(schema_property: dict[str, Any]) -> str:
    return {
        "string": "string",
        "integer": "long",
        "number": "decimal",
        "boolean": "bool",
        "object": "object",
        "array": "IReadOnlyList<object>",
    }.get(json_type(schema_property), "object")


def python_type(schema_property: dict[str, Any]) -> str:
    return {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "object": "dict[str, Any]",
        "array": "list[Any]",
    }.get(json_type(schema_property), "Any")


def generate_csharp(schemas: list[dict[str, Any]]) -> str:
    lines = [
        "// <auto-generated />",
        "// Generated from packages/contracts/*.schema.json. Do not edit manually.",
        "using System.Collections.Generic;",
        "",
        "namespace WarehouseTwin.Contracts;",
        "",
    ]
    for schema in schemas:
        title = schema["title"]
        properties = schema["properties"]
        lines.append(f"public sealed record {title}(")
        params = [
            f"    {csharp_type(prop_schema)} {name}"
            for name, prop_schema in properties.items()
        ]
        lines.append(",\n".join(params))
        lines.append(");")
        lines.append("")
    return "\n".join(lines)


def generate_python(schemas: list[dict[str, Any]]) -> str:
    lines = [
        "# <auto-generated>",
        "# Generated from packages/contracts/*.schema.json. Do not edit manually.",
        "from dataclasses import dataclass",
        "from typing import Any",
        "",
        "",
    ]
    for schema in schemas:
        title = schema["title"]
        properties = schema["properties"]
        lines.append("@dataclass(frozen=True)")
        lines.append(f"class {title}:")
        if properties:
            for name, prop_schema in properties.items():
                lines.append(f"    {name}: {python_type(prop_schema)}")
        else:
            lines.append("    pass")
        lines.append("")
    return "\n".join(lines)


def generate_manifest(paths: list[Path]) -> str:
    schemas = []
    for path in paths:
        data = path.read_bytes()
        schemas.append(
            {
                "path": path.relative_to(ROOT).as_posix(),
                "sha256": hashlib.sha256(data).hexdigest(),
            }
        )
    manifest = {
        "generated_at": "deterministic",
        "generator_version": GENERATOR_VERSION,
        "schemas": schemas,
    }
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def main() -> int:
    paths = schema_paths()
    if not paths:
        print("ERROR: no schema files found.", file=sys.stderr)
        return 1

    try:
        schemas = [load_schema(path) for path in paths]
    except (json.JSONDecodeError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    CSharp_OUT.parent.mkdir(parents=True, exist_ok=True)
    PYTHON_OUT.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_OUT.parent.mkdir(parents=True, exist_ok=True)

    CSharp_OUT.write_text(generate_csharp(schemas), encoding="utf-8")
    PYTHON_OUT.write_text(generate_python(schemas), encoding="utf-8")
    MANIFEST_OUT.write_text(generate_manifest(paths), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
